### ISSUE TITLE
Docs.rs build failures

### ISSUE THREAD

**Issue by khionu** [drone-os/drone-core#1]
I checked for 0.8.3 and 0.8.2, but I'm not sure how far back it goes.

**Comment by valff** [comment]
It is because docs.rs can't set `procmacro2_semver_exempt` config flag for `proc-macro2` crate. Here is a similar issue: alexcrichton/proc-macro2#89.

The plan of resolving this is to eventually move from crates.io and docs.rs to self-hosting. Meanwhile you can build the docs locally with: `RUSTC_WRAPPER=./rustc-wrapper.sh cargo doc`.

**Comment by valff** [comment]
The documentation is now self-hosted at https://api.drone-os.com/drone-core/0.10/
